"""
utils/validators.py — Input sanitization and domain validation.

All validation is done BEFORE cryptographic operations to fail fast
on obviously invalid inputs without wasting compute.
"""

import re
from fastapi import HTTPException
from app.config import P, Q

# Username: 3–50 chars, alphanumeric + underscore + hyphen
_USERNAME_RE = re.compile(r"^[a-zA-Z0-9_\-]{3,50}$")


def validate_username(username: str) -> str:
    """
    Sanitize and validate a username.

    Rules:
      - 3 to 50 characters
      - Only a-z, A-Z, 0-9, underscore, hyphen

    Returns the stripped username or raises HTTP 400.
    """
    username = username.strip()
    if not _USERNAME_RE.match(username):
        raise HTTPException(
            status_code=400,
            detail=(
                "Invalid username. Must be 3–50 characters and contain only "
                "letters, digits, underscores, or hyphens."
            ),
        )
    return username


def validate_public_key(y: int) -> None:
    """
    Validate that y is a legitimate public key in the Schnorr group.

    Two checks:
      1. 1 < y < P  — y must be in the multiplicative group Z*_P
      2. y^Q ≡ 1 (mod P) — y must be in the subgroup of order Q
         (i.e., y is a quadratic residue mod P, generated by G)

    The second check prevents small-subgroup attacks where an attacker
    sends a y outside the Schnorr subgroup.

    Raises HTTP 400 if either check fails.
    """
    if not (1 < y < P):
        raise HTTPException(
            status_code=400,
            detail="Invalid public key: must satisfy 1 < y < P.",
        )
    # Subgroup membership check: y^Q mod P must equal 1
    if pow(y, Q, P) != 1:
        raise HTTPException(
            status_code=400,
            detail="Invalid public key: not in the Schnorr subgroup (y^Q mod P ≠ 1).",
        )


def validate_commitment(r: int) -> None:
    """
    Validate the prover's commitment r = G^k mod P.

    Must satisfy: 1 < r < P
    Values of 0 or 1 would trivially break the protocol.

    Raises HTTP 400 if invalid.
    """
    if not (1 < r < P):
        raise HTTPException(
            status_code=400,
            detail="Invalid commitment: must satisfy 1 < r < P.",
        )


def validate_response(s: int) -> None:
    """
    Validate the prover's response s = (k + e·x) mod Q.

    Must satisfy: 0 <= s < Q
    Exponent arithmetic is always done mod Q.

    Raises HTTP 400 if invalid.
    """
    if not (0 <= s < Q):
        raise HTTPException(
            status_code=400,
            detail="Invalid response: must satisfy 0 ≤ s < Q.",
        )