"""
services/session_manager.py — In-memory challenge session store.

Sessions are short-lived (60s TTL) and single-use.
They tie a commitment r and challenge e to a specific login attempt,
identified by a random session_id instead of username.

Using session_id (rather than username) as the key allows multiple
simultaneous login attempts from the same or different clients.

Thread safety note:
  Python's GIL makes dictionary operations atomic for simple get/set/delete.
  For a production multi-process deployment, replace this with Redis
  using SETNX + EXPIRE for atomic session creation and TTL enforcement.
"""

import secrets
import time
import logging
from dataclasses import dataclass, field
from app.config import SESSION_TTL_SECONDS

logger = logging.getLogger(__name__)


@dataclass
class ChallengeSession:
    """
    A single challenge session created during the commit step.

    Fields:
        session_id   — random hex token, the session's primary key
        username     — which user is authenticating
        commitment_r — G^k mod P sent by the prover
        challenge_e  — random challenge sent to the prover
        created_at   — Unix timestamp for TTL enforcement
    """
    session_id: str
    username: str
    commitment_r: int
    challenge_e: int
    created_at: float = field(default_factory=time.time)

    def is_expired(self) -> bool:
        """Return True if the session has exceeded SESSION_TTL_SECONDS."""
        return (time.time() - self.created_at) > SESSION_TTL_SECONDS


# In-memory store: session_id → ChallengeSession
_sessions: dict[str, ChallengeSession] = {}


def create_session(username: str, commitment_r: int, challenge_e: int) -> str:
    """
    Create a new challenge session and return its session_id.

    session_id is a 32-character hex string (128 bits of entropy)
    generated by secrets.token_hex(), which uses the OS CSPRNG.

    128 bits makes brute-forcing session IDs computationally infeasible.
    """
    session_id = secrets.token_hex(16)
    _sessions[session_id] = ChallengeSession(
        session_id=session_id,
        username=username,
        commitment_r=commitment_r,
        challenge_e=challenge_e,
    )
    logger.info("Session created for user '%s' | session_id=%s", username, session_id)
    return session_id


def get_and_consume_session(session_id: str) -> ChallengeSession | None:
    """
    Retrieve and immediately delete a session (single-use).

    Returns:
        ChallengeSession — if found and not expired
        None             — if not found or expired

    The session is deleted regardless of outcome (expired or valid).
    This prevents replay attacks: each session_id can only be used once.
    """
    session = _sessions.pop(session_id, None)

    if session is None:
        logger.warning("Session not found: %s", session_id)
        return None

    if session.is_expired():
        logger.warning(
            "Session expired for user '%s' | session_id=%s | age=%.1fs",
            session.username,
            session_id,
            time.time() - session.created_at,
        )
        return None

    logger.info(
        "Session consumed for user '%s' | session_id=%s",
        session.username,
        session_id,
    )
    return session


def purge_expired_sessions() -> int:
    """
    Remove all expired sessions from the store.

    Should be called periodically (e.g., via a background task or
    a scheduled job) to prevent unbounded memory growth.

    Returns the number of sessions purged.
    """
    expired = [sid for sid, s in _sessions.items() if s.is_expired()]
    for sid in expired:
        del _sessions[sid]

    if expired:
        logger.info("Purged %d expired session(s).", len(expired))

    return len(expired)