"""
config.py — Global configuration and cryptographic domain parameters.

Schnorr Protocol Parameters:
─────────────────────────────────────────────────────────────────────
P is a 512-bit safe prime: P = 2Q + 1
Q is a Sophie Germain prime: Q = (P - 1) / 2
G = 2 is a generator of the subgroup of order Q in Z*_P

A safe prime guarantees the subgroup structure needed for Schnorr:
  - The subgroup generated by G has prime order Q
  - Computing discrete logs in this group is computationally infeasible
─────────────────────────────────────────────────────────────────────
"""

# ── Schnorr Domain Parameters ─────────────────────────────────────────────────

# 512-bit safe prime P = 2Q + 1
P = 0x9B0F3D5E1763A9C8D5A12398AFBCDE76123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF

# Subgroup order Q = (P - 1) / 2
# All exponents and challenges are reduced mod Q
Q = (P - 1) // 2

# Generator G = 2
# G^Q ≡ 1 (mod P) — G has order Q in Z*_P
G = 2

# ── Session Configuration ──────────────────────────────────────────────────────

# Challenge sessions expire after 60 seconds
SESSION_TTL_SECONDS = 60

# ── MongoDB Configuration ──────────────────────────────────────────────────────

MONGO_URI = "mongodb://localhost:27017"
MONGO_DB_NAME = "zkp_auth"

# ── App Configuration ──────────────────────────────────────────────────────────

APP_HOST = "127.0.0.1"
APP_PORT = 8000
APP_TITLE = "ZKP Auth — Schnorr Identification Protocol"
APP_VERSION = "1.0.0"