/**
 * Schnorr Identification Protocol — Pure BigInt Implementation
 *
 * PROTOCOL OVERVIEW:
 * ─────────────────────────────────────────────────────────────
 * We operate in Z*_p, a multiplicative group of integers mod p.
 * The subgroup of order q is generated by g.
 *
 *   Public parameters:  p (prime), q (subgroup order), g (generator)
 *   Secret key (prover):  x ∈ [1, q-1]
 *   Public key:           y = g^x mod p
 *
 * LOGIN HANDSHAKE:
 *   1. Prover picks random k, sends commitment r = g^k mod p
 *   2. Verifier sends random challenge e
 *   3. Prover computes response s = (k + e·x) mod q
 *   4. Verifier checks: g^s mod p == r · y^e mod p
 *
 * WHY IT'S ZERO-KNOWLEDGE:
 *   The verifier learns nothing about x because k is ephemeral
 *   and s is indistinguishable from a random number mod q.
 * ─────────────────────────────────────────────────────────────
 */

// ── Domain Parameters ────────────────────────────────────────
// Small values for demonstration. In production:
//   p ~ 2048-bit prime, q ~ 256-bit prime, g a quadratic residue mod p.
export const p = 0xFFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7EDEE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3DC2007CB8A163BF0598DA48361C55D39A69163FA8FD24CF5F83655D23DCA3AD961C62F356208552BB9ED529077096966D670C354E4ABC9804F1746C08CA237327FFFFFFFFFFFFFFFFn;
export const q = (0xFFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7EDEE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3DC2007CB8A163BF0598DA48361C55D39A69163FA8FD24CF5F83655D23DCA3AD961C62F356208552BB9ED529077096966D670C354E4ABC9804F1746C08CA237327FFFFFFFFFFFFFFFFn - 1n) / 2n;
export const g = 2n;

/**
 * Modular Exponentiation — Square-and-Multiply Algorithm
 *
 * Computes (base ^ exp) mod mod efficiently.
 * Naïve approach: compute base^exp then reduce — astronomically slow for
 * cryptographic sizes (exp can be 256+ bits). Instead we exploit:
 *
 *   (a · b) mod m = ((a mod m) · (b mod m)) mod m
 *
 * so we reduce at every step. Time complexity: O(log exp) multiplications.
 *
 * Example: 2^11 mod 23
 *   11 in binary = 1011
 *   acc starts at 1, base starts at 2
 *   bit 0 (LSB) = 1 → acc = (1·2) mod 23 = 2,  base = 4
 *   bit 1        = 1 → acc = (2·4) mod 23 = 8,  base = 16
 *   bit 2        = 0 → acc unchanged = 8,         base = (16·16) mod 23 = 3
 *   bit 3 (MSB) = 1 → acc = (8·3) mod 23 = 1
 *   Result: 2^11 mod 23 = 1  ✓ (since q=11 is the order)
 *
 * @param {BigInt} base
 * @param {BigInt} exp
 * @param {BigInt} mod
 * @returns {BigInt}
 */
export function modPow(base, exp, mod) {
  if (mod === 1n) return 0n;

  let result = 1n;
  base = base % mod; // Initial reduction

  while (exp > 0n) {
    // If current bit of exp is 1, multiply accumulator by current base
    if (exp % 2n === 1n) {
      result = (result * base) % mod;
    }
    // Square the base for the next bit position
    base = (base * base) % mod;
    // Shift exp right by 1 bit (divide by 2, discard remainder)
    exp = exp / 2n;
  }

  return result;
}

/**
 * Cryptographically Random BigInt in [1, max-1]
 *
 * JavaScript's Math.random() is NOT cryptographically secure —
 * it uses a deterministic PRNG unsuitable for secret key material.
 *
 * Instead we use window.crypto.getRandomValues() which reads from
 * the OS CSPRNG (e.g., /dev/urandom on Linux, CryptGenRandom on Windows).
 *
 * We generate 32 random bytes (256 bits) and interpret them as a
 * big-endian unsigned integer, then reduce modulo max.
 *
 * NOTE: For tiny q (like q=11), this produces a biased result, but
 * it's sufficient for this demonstration. Production code would use
 * rejection sampling to eliminate modular bias.
 *
 * @param {BigInt} max - exclusive upper bound
 * @returns {BigInt} random BigInt in [1, max-1]
 */
export function randomBigInt(max) {
  // 32 bytes = 256 bits of entropy
  const bytes = new Uint8Array(32);
  window.crypto.getRandomValues(bytes);

  // Reconstruct a BigInt from the byte array (big-endian)
  // bytes[0] is the most significant byte
  let value = 0n;
  for (const byte of bytes) {
    value = (value << 8n) | BigInt(byte);
  }

  // Reduce mod (max-1) then add 1 to get [1, max-1]
  return (value % (max - 1n)) + 1n;
}

// ── Registration ─────────────────────────────────────────────

/**
 * Generate a fresh keypair for registration.
 *
 * Secret key: x ← random ∈ [1, q-1]
 * Public key: y = g^x mod p
 *
 * The secret key is the "password" — never sent to the server.
 * The public key y is stored server-side and used to verify proofs.
 *
 * @returns {{ x: BigInt, y: BigInt, xHex: string, yHex: string }}
 */
export function generateKeypair() {
  const x = randomBigInt(q); // Secret key x ∈ [1, q-1]
  const y = modPow(g, x, p); // Public key y = g^x mod p
  return {
    x,
    y,
    xHex: x.toString(16).padStart(4, "0"),
    yHex: y.toString(16).padStart(4, "0"),
  };
}

// ── Login Step 1: Commitment ──────────────────────────────────

/**
 * Generate the prover's commitment for the first round.
 *
 * The prover picks a fresh ephemeral secret k, and commits to it
 * by publishing r = g^k mod p. Crucially, k must be:
 *   - Never reused (each login picks a fresh k)
 *   - Kept secret until the protocol completes
 *
 * Reusing k leaks x: if s1 = k + e1·x and s2 = k + e2·x,
 * then s1 - s2 = (e1 - e2)·x → x = (s1-s2)/(e1-e2) mod q.
 *
 * @returns {{ k: BigInt, r: BigInt, rHex: string }}
 */
export function generateCommitment() {
  const k = randomBigInt(q); // Ephemeral secret k ∈ [1, q-1]
  const r = modPow(g, k, p); // Commitment r = g^k mod p
  return {
    k,
    r,
    rHex: r.toString(16).padStart(4, "0"),
  };
}

// ── Login Step 2: Response ────────────────────────────────────

/**
 * Compute the prover's response to the verifier's challenge.
 *
 * s = (k + e·x) mod q
 *
 * Mathematical intuition:
 *   The verifier will check: g^s ≡ r · y^e (mod p)
 *
 *   Proof: g^s = g^(k + e·x) = g^k · g^(e·x) = g^k · (g^x)^e = r · y^e ✓
 *
 * This works because exponent arithmetic is done mod q (the group order),
 * while base arithmetic is mod p.
 *
 * @param {BigInt} k - ephemeral secret from commitment step
 * @param {BigInt} e - challenge from verifier
 * @param {BigInt} x - prover's long-term secret key
 * @returns {{ s: BigInt, sHex: string }}
 */
export function computeResponse(k, e, x) {
  // s = (k + e · x) mod q
  // FIX: Force a strictly positive mathematical modulus calculation
  let s = (k + e * x) % q;
  if (s < 0n) {
    s = s + q;
  }
  
  return {
    s,
    sHex: s.toString(16).padStart(4, "0"),
  };
}

// ── Verification (normally server-side) ──────────────────────

/**
 * Verify a Schnorr proof — this runs on the SERVER in reality.
 * Included here to simulate the backend's check.
 *
 * Check: g^s ≡ r · y^e (mod p)
 *
 * If the prover knows x such that y = g^x, they can always produce
 * a valid s. A cheating prover who doesn't know x cannot satisfy this
 * equation with non-negligible probability (hardness of discrete log).
 *
 * @param {BigInt} y - public key (from registration)
 * @param {BigInt} r - commitment (from login step 1)
 * @param {BigInt} e - challenge
 * @param {BigInt} s - response (from login step 2)
 * @returns {boolean}
 */
export function verify(y, r, e, s) {
  const lhs = modPow(g, s, p); // g^s mod p
  const rhs = (r * modPow(y, e, p)) % p; // r · y^e mod p
  return lhs === rhs;
}

/**
 * Simulate receiving a random challenge from the server.
 * In a real protocol, e comes from the server after receiving r.
 * It must be unpredictable to prevent commitment grinding attacks.
 *
 * @returns {BigInt} random challenge e ∈ [1, q-1]
 */
export function generateChallenge() {
  return randomBigInt(q);
}